eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="$HOME/.local/bin:$HOME/Library/Python/3.12/bin:$PATH"
export HERMES_SHARED="/Users/Shared"
export HERMES_CODE="/Users/Shared/code"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR="${EDITOR:-nano}"
