export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(
  git
  github
  z
  zsh-autosuggestions
  zsh-syntax-highlighting
  history-substring-search
)

export HOMEBREW_NO_ANALYTICS=1

if [[ -s "$ZSH/oh-my-zsh.sh" ]]; then
  source "$ZSH/oh-my-zsh.sh"
fi

[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

export PATH="./bin:./node_modules/.bin:$HOME/.local/bin:$HOME/Library/Python/3.12/bin:$PATH"
export HERMES_SHARED="/Users/Shared"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR="${EDITOR:-nano}"
export COREPACK_ENABLE_DOWNLOAD_PROMPT=0
export COREPACK_ENABLE_STRICT=1

alias p='pnpm'
alias npm='pnpm'
alias npx='pnpm dlx'
alias yarn='pnpm'
alias yarnpkg='pnpm'

export NVM_DIR="$HOME/.nvm"
if [[ -s "$NVM_DIR/nvm.sh" ]]; then
  source "$NVM_DIR/nvm.sh"
fi

if [[ -s "$NVM_DIR/bash_completion" ]]; then
  source "$NVM_DIR/bash_completion"
fi
